/* GENERATED by gen_fieldcase.py — curated from six REAL Google Analytics
   exports (an anonymised UK electronics retailer, 25 Aug – 3 Nov 2015).
   Real data, lightly curated: long-tail rows are aggregated into
   '(N other …)' rows; every number that matters is untouched.
   Do not hand-edit — regenerate from the source workbooks. */
export const FIELD_DATA = {
  "channels": {
    "rows": [
      {
        "id": "ch-paidsearch",
        "name": "Paid Search",
        "sessions": 160936,
        "pctNew": 0.6925,
        "newUsers": 111441,
        "bounce": 0.806,
        "pages": 1.91,
        "dur": 63.71,
        "conv": 0.0119,
        "trans": 1913,
        "revenue": 759678.72
      },
      {
        "id": "ch-organicsearch",
        "name": "Organic Search",
        "sessions": 38911,
        "pctNew": 0.6242,
        "newUsers": 24290,
        "bounce": 0.6635,
        "pages": 2.9,
        "dur": 134.89,
        "conv": 0.0125,
        "trans": 485,
        "revenue": 277542.5
      },
      {
        "id": "ch-referral",
        "name": "Referral",
        "sessions": 15167,
        "pctNew": 0.3248,
        "newUsers": 4926,
        "bounce": 0.5631,
        "pages": 3.05,
        "dur": 190.15,
        "conv": 0.1598,
        "trans": 2423,
        "revenue": 1673332.95
      },
      {
        "id": "ch-direct",
        "name": "Direct",
        "sessions": 15019,
        "pctNew": 0.7405,
        "newUsers": 11122,
        "bounce": 0.5118,
        "pages": 3.72,
        "dur": 169.22,
        "conv": 0.0254,
        "trans": 381,
        "revenue": 575501.8
      },
      {
        "id": "ch-social",
        "name": "Social",
        "sessions": 95,
        "pctNew": 0.6,
        "newUsers": 57,
        "bounce": 0.6211,
        "pages": 2.33,
        "dur": 124.83,
        "conv": 0.0105,
        "trans": 1,
        "revenue": 940.7
      }
    ],
    "total": {
      "id": "ch-total",
      "name": "Total",
      "sessions": 230128,
      "pctNew": 0.6598,
      "newUsers": 151836,
      "bounce": 0.7466,
      "pages": 2.27,
      "dur": 90.99,
      "conv": 0.0226,
      "trans": 5203,
      "revenue": 3286996.67
    }
  },
  "daily": [
    {
      "date": "25 Aug",
      "sessions": 3877
    },
    {
      "date": "26 Aug",
      "sessions": 3728
    },
    {
      "date": "27 Aug",
      "sessions": 3130
    },
    {
      "date": "28 Aug",
      "sessions": 2755
    },
    {
      "date": "29 Aug",
      "sessions": 1440
    },
    {
      "date": "30 Aug",
      "sessions": 1741
    },
    {
      "date": "31 Aug",
      "sessions": 2505
    },
    {
      "date": "01 Sep",
      "sessions": 3512
    },
    {
      "date": "02 Sep",
      "sessions": 3590
    },
    {
      "date": "03 Sep",
      "sessions": 3417
    },
    {
      "date": "04 Sep",
      "sessions": 2990
    },
    {
      "date": "05 Sep",
      "sessions": 1617
    },
    {
      "date": "06 Sep",
      "sessions": 1754
    },
    {
      "date": "07 Sep",
      "sessions": 3302
    },
    {
      "date": "08 Sep",
      "sessions": 3558
    },
    {
      "date": "09 Sep",
      "sessions": 3490
    },
    {
      "date": "10 Sep",
      "sessions": 3478
    },
    {
      "date": "11 Sep",
      "sessions": 2902
    },
    {
      "date": "12 Sep",
      "sessions": 1545
    },
    {
      "date": "13 Sep",
      "sessions": 1794
    },
    {
      "date": "14 Sep",
      "sessions": 3354
    },
    {
      "date": "15 Sep",
      "sessions": 3354
    },
    {
      "date": "16 Sep",
      "sessions": 3578
    },
    {
      "date": "17 Sep",
      "sessions": 3374
    },
    {
      "date": "18 Sep",
      "sessions": 3195
    },
    {
      "date": "19 Sep",
      "sessions": 1706
    },
    {
      "date": "20 Sep",
      "sessions": 1955
    },
    {
      "date": "21 Sep",
      "sessions": 3807
    },
    {
      "date": "22 Sep",
      "sessions": 4039
    },
    {
      "date": "23 Sep",
      "sessions": 3734
    },
    {
      "date": "24 Sep",
      "sessions": 3456
    },
    {
      "date": "25 Sep",
      "sessions": 2988
    },
    {
      "date": "26 Sep",
      "sessions": 1461
    },
    {
      "date": "27 Sep",
      "sessions": 1764
    },
    {
      "date": "28 Sep",
      "sessions": 3287
    },
    {
      "date": "29 Sep",
      "sessions": 3575
    },
    {
      "date": "30 Sep",
      "sessions": 3588
    },
    {
      "date": "01 Oct",
      "sessions": 3593
    },
    {
      "date": "02 Oct",
      "sessions": 3547
    },
    {
      "date": "03 Oct",
      "sessions": 2722
    },
    {
      "date": "04 Oct",
      "sessions": 2397
    },
    {
      "date": "05 Oct",
      "sessions": 4499
    },
    {
      "date": "06 Oct",
      "sessions": 5249
    },
    {
      "date": "07 Oct",
      "sessions": 4419
    },
    {
      "date": "08 Oct",
      "sessions": 4630
    },
    {
      "date": "09 Oct",
      "sessions": 3528
    },
    {
      "date": "10 Oct",
      "sessions": 2220
    },
    {
      "date": "11 Oct",
      "sessions": 2281
    },
    {
      "date": "12 Oct",
      "sessions": 4303
    },
    {
      "date": "13 Oct",
      "sessions": 4616
    },
    {
      "date": "14 Oct",
      "sessions": 4382
    },
    {
      "date": "15 Oct",
      "sessions": 3975
    },
    {
      "date": "16 Oct",
      "sessions": 3487
    },
    {
      "date": "17 Oct",
      "sessions": 1914
    },
    {
      "date": "18 Oct",
      "sessions": 2116
    },
    {
      "date": "19 Oct",
      "sessions": 4267
    },
    {
      "date": "20 Oct",
      "sessions": 4264
    },
    {
      "date": "21 Oct",
      "sessions": 4118
    },
    {
      "date": "22 Oct",
      "sessions": 3828
    },
    {
      "date": "23 Oct",
      "sessions": 3516
    },
    {
      "date": "24 Oct",
      "sessions": 1990
    },
    {
      "date": "25 Oct",
      "sessions": 2331
    },
    {
      "date": "26 Oct",
      "sessions": 3846
    },
    {
      "date": "27 Oct",
      "sessions": 4145
    },
    {
      "date": "28 Oct",
      "sessions": 3994
    },
    {
      "date": "29 Oct",
      "sessions": 3668
    },
    {
      "date": "30 Oct",
      "sessions": 4451
    },
    {
      "date": "31 Oct",
      "sessions": 2414
    },
    {
      "date": "01 Nov",
      "sessions": 2320
    },
    {
      "date": "02 Nov",
      "sessions": 4398
    },
    {
      "date": "03 Nov",
      "sessions": 4360
    }
  ],
  "sourceMedium": {
    "rows": [
      {
        "id": "sm-google-cpc",
        "name": "google / cpc",
        "sessions": 160936,
        "pctNew": 0.6925,
        "newUsers": 111441,
        "bounce": 0.806,
        "pages": 1.91,
        "dur": 63.71,
        "conv": 0.0119,
        "trans": 1913,
        "revenue": 759678.72
      },
      {
        "id": "sm-google-organic",
        "name": "google / organic",
        "sessions": 37657,
        "pctNew": 0.6221,
        "newUsers": 23428,
        "bounce": 0.6673,
        "pages": 2.87,
        "dur": 134.36,
        "conv": 0.0122,
        "trans": 458,
        "revenue": 260178.36
      },
      {
        "id": "sm-direct-none",
        "name": "(direct) / (none)",
        "sessions": 15019,
        "pctNew": 0.7405,
        "newUsers": 11122,
        "bounce": 0.5118,
        "pages": 3.72,
        "dur": 169.22,
        "conv": 0.0254,
        "trans": 381,
        "revenue": 575501.8
      },
      {
        "id": "sm-google-co-uk-referral",
        "name": "google.co.uk / referral",
        "sessions": 3711,
        "pctNew": 0.0674,
        "newUsers": 250,
        "bounce": 0.9003,
        "pages": 1.13,
        "dur": 28.66,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-paypal-com-referral",
        "name": "paypal.com / referral",
        "sessions": 3626,
        "pctNew": 0.0025,
        "newUsers": 9,
        "bounce": 0.1561,
        "pages": 3.86,
        "dur": 187.52,
        "conv": 0.5292,
        "trans": 1919,
        "revenue": 533198.38
      },
      {
        "id": "sm-hotukdeals-com-referral",
        "name": "hotukdeals.com / referral",
        "sessions": 2236,
        "pctNew": 0.7393,
        "newUsers": 1653,
        "bounce": 0.7366,
        "pages": 1.99,
        "dur": 72.92,
        "conv": 0.0004,
        "trans": 1,
        "revenue": 439.87
      },
      {
        "id": "sm-pricespy-co-uk-referral",
        "name": "pricespy.co.uk / referral",
        "sessions": 1092,
        "pctNew": 0.6117,
        "newUsers": 668,
        "bounce": 0.6474,
        "pages": 2.66,
        "dur": 131.76,
        "conv": 0.0119,
        "trans": 13,
        "revenue": 12065.4
      },
      {
        "id": "sm-idealo-co-uk-referral",
        "name": "idealo.co.uk / referral",
        "sessions": 1001,
        "pctNew": 0.6014,
        "newUsers": 602,
        "bounce": 0.6444,
        "pages": 2.53,
        "dur": 115.01,
        "conv": 0.011,
        "trans": 11,
        "revenue": 3149.68
      },
      {
        "id": "sm-bing-organic",
        "name": "bing / organic",
        "sessions": 972,
        "pctNew": 0.678,
        "newUsers": 659,
        "bounce": 0.5453,
        "pages": 3.86,
        "dur": 138.89,
        "conv": 0.0247,
        "trans": 24,
        "revenue": 16807
      },
      {
        "id": "sm-pricehunter-co-uk-referral",
        "name": "pricehunter.co.uk / referral",
        "sessions": 483,
        "pctNew": 0.8799,
        "newUsers": 425,
        "bounce": 0.706,
        "pages": 2.02,
        "dur": 90.09,
        "conv": 0.0021,
        "trans": 1,
        "revenue": 54.29
      },
      {
        "id": "sm-yahoo-organic",
        "name": "yahoo / organic",
        "sessions": 257,
        "pctNew": 0.7432,
        "newUsers": 191,
        "bounce": 0.5875,
        "pages": 3.47,
        "dur": 182.09,
        "conv": 0.0117,
        "trans": 3,
        "revenue": 557.14
      },
      {
        "id": "sm-techradar-com-referral",
        "name": "techradar.com / referral",
        "sessions": 210,
        "pctNew": 0.981,
        "newUsers": 206,
        "bounce": 0.9333,
        "pages": 1.15,
        "dur": 6.75,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-sandbox-paypal-com-referral",
        "name": "sandbox.paypal.com / referral",
        "sessions": 97,
        "pctNew": 0,
        "newUsers": 0,
        "bounce": 0.1753,
        "pages": 1.35,
        "dur": 24.19,
        "conv": 0.7835,
        "trans": 76,
        "revenue": 386975.06
      },
      {
        "id": "sm-expertreviews-co-uk-referral",
        "name": "expertreviews.co.uk / referral",
        "sessions": 95,
        "pctNew": 0.8737,
        "newUsers": 83,
        "bounce": 0.5474,
        "pages": 3.4,
        "dur": 93.66,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-duckduckgo-com-referral",
        "name": "duckduckgo.com / referral",
        "sessions": 81,
        "pctNew": 0.7284,
        "newUsers": 59,
        "bounce": 0.6296,
        "pages": 4.38,
        "dur": 176.8,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-kagoo-co-uk-referral",
        "name": "kagoo.co.uk / referral",
        "sessions": 77,
        "pctNew": 0.9351,
        "newUsers": 72,
        "bounce": 0.5714,
        "pages": 1.84,
        "dur": 53.29,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-live-sagepay-com-referral",
        "name": "live.sagepay.com / referral",
        "sessions": 46,
        "pctNew": 0,
        "newUsers": 0,
        "bounce": 0.1087,
        "pages": 10.98,
        "dur": 573.04,
        "conv": 0.087,
        "trans": 4,
        "revenue": 2243.94
      },
      {
        "id": "sm-192-168-1-100-7777-referral",
        "name": "192.168.1.100:7777 / referral",
        "sessions": 34,
        "pctNew": 0.2647,
        "newUsers": 9,
        "bounce": 0.9412,
        "pages": 1.06,
        "dur": 27.97,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-2staging-chrichton-co-uk-referral",
        "name": "2staging.chrichton.co.uk / referral",
        "sessions": 20,
        "pctNew": 0,
        "newUsers": 0,
        "bounce": 0.3,
        "pages": 9.6,
        "dur": 377.65,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-workshop-chrichton-co-uk-referral",
        "name": "workshop.chrichton.co.uk / referral",
        "sessions": 16,
        "pctNew": 0.0625,
        "newUsers": 1,
        "bounce": 0.5625,
        "pages": 6.38,
        "dur": 454.38,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "sm-myvouchercodes-co-uk-referral",
        "name": "myvouchercodes.co.uk / referral",
        "sessions": 63,
        "pctNew": 0.1429,
        "newUsers": 9,
        "bounce": 0.3968,
        "pages": 4.92,
        "dur": 279.37,
        "conv": 0.0794,
        "trans": 5,
        "revenue": 2048.57
      },
      {
        "id": "sm-voucherslug-co-uk-referral",
        "name": "voucherslug.co.uk / referral",
        "sessions": 23,
        "pctNew": 0.0435,
        "newUsers": 1,
        "bounce": 0.2609,
        "pages": 5.83,
        "dur": 175.78,
        "conv": 0.087,
        "trans": 2,
        "revenue": 2848.03
      },
      {
        "id": "sm-mail-google-com-referral",
        "name": "mail.google.com / referral",
        "sessions": 43,
        "pctNew": 0.4419,
        "newUsers": 19,
        "bounce": 0.2791,
        "pages": 3.86,
        "dur": 121.35,
        "conv": 0.0465,
        "trans": 2,
        "revenue": 1032.99
      },
      {
        "id": "sm-facebook-com-referral",
        "name": "facebook.com / referral",
        "sessions": 40,
        "pctNew": 0.55,
        "newUsers": 22,
        "bounce": 0.525,
        "pages": 2.85,
        "dur": 181.68,
        "conv": 0.025,
        "trans": 1,
        "revenue": 940.7
      },
      {
        "id": "sm-other",
        "name": "(all other sources)",
        "sessions": 2293,
        "pctNew": 0.3956,
        "newUsers": 907,
        "bounce": 0.3864,
        "pages": 6.49,
        "dur": 673.38,
        "conv": 0.1696,
        "trans": 389,
        "revenue": 729276.74
      }
    ]
  },
  "age": {
    "rows": [
      {
        "id": "age-35-44",
        "name": "35-44",
        "sessions": 44295,
        "pctNew": 0.593,
        "newUsers": 26265,
        "bounce": 0.7474,
        "pages": 2.28,
        "dur": 90.28,
        "conv": 0.0244,
        "trans": 1079,
        "revenue": 562173.83
      },
      {
        "id": "age-25-34",
        "name": "25-34",
        "sessions": 33184,
        "pctNew": 0.6079,
        "newUsers": 20172,
        "bounce": 0.7683,
        "pages": 2.16,
        "dur": 98.66,
        "conv": 0.021,
        "trans": 696,
        "revenue": 500723.79
      },
      {
        "id": "age-45-54",
        "name": "45-54",
        "sessions": 25570,
        "pctNew": 0.6118,
        "newUsers": 15644,
        "bounce": 0.7244,
        "pages": 2.38,
        "dur": 94.39,
        "conv": 0.026,
        "trans": 666,
        "revenue": 261406.48
      },
      {
        "id": "age-18-24",
        "name": "18-24",
        "sessions": 13199,
        "pctNew": 0.6277,
        "newUsers": 8285,
        "bounce": 0.8273,
        "pages": 1.83,
        "dur": 67.9,
        "conv": 0.0136,
        "trans": 179,
        "revenue": 79610.99
      },
      {
        "id": "age-55-64",
        "name": "55-64",
        "sessions": 10341,
        "pctNew": 0.6683,
        "newUsers": 6911,
        "bounce": 0.7199,
        "pages": 2.38,
        "dur": 88.29,
        "conv": 0.0239,
        "trans": 247,
        "revenue": 80920.25
      },
      {
        "id": "age-65plus",
        "name": "65+",
        "sessions": 6950,
        "pctNew": 0.6803,
        "newUsers": 4728,
        "bounce": 0.6807,
        "pages": 2.6,
        "dur": 104.67,
        "conv": 0.0276,
        "trans": 192,
        "revenue": 54699.08
      }
    ],
    "total": {
      "id": "age-total",
      "name": "Total",
      "sessions": 133539,
      "pctNew": 0.6141,
      "newUsers": 82005,
      "bounce": 0.7505,
      "pages": 2.25,
      "dur": 91.53,
      "conv": 0.0229,
      "trans": 3059,
      "revenue": 1539534.42
    }
  },
  "device": {
    "rows": [
      {
        "id": "dev-desktop",
        "name": "Desktop",
        "sessions": 176643,
        "pctNew": 0.6343,
        "newUsers": 112040,
        "bounce": 0.735,
        "pages": 2.41,
        "dur": 101.04,
        "conv": 0.0252,
        "trans": 4457,
        "revenue": 2714702.61
      },
      {
        "id": "dev-mobile",
        "name": "Mobile",
        "sessions": 33626,
        "pctNew": 0.7628,
        "newUsers": 25649,
        "bounce": 0.8092,
        "pages": 1.68,
        "dur": 48.42,
        "conv": 0.0121,
        "trans": 407,
        "revenue": 425227.83
      },
      {
        "id": "dev-tablet",
        "name": "Tablet",
        "sessions": 19859,
        "pctNew": 0.7124,
        "newUsers": 14147,
        "bounce": 0.7438,
        "pages": 2.05,
        "dur": 73.69,
        "conv": 0.0171,
        "trans": 339,
        "revenue": 147066.23
      }
    ],
    "total": {
      "id": "dev-total",
      "name": "Total",
      "sessions": 230128,
      "pctNew": 0.6598,
      "newUsers": 151836,
      "bounce": 0.7466,
      "pages": 2.27,
      "dur": 90.99,
      "conv": 0.0226,
      "trans": 5203,
      "revenue": 3286996.67
    }
  },
  "landingPages": {
    "rows": [
      {
        "id": "lp-0",
        "name": "/",
        "sessions": 14758,
        "pctNew": 0.4351,
        "newUsers": 6421,
        "bounce": 0.1814,
        "pages": 6.95,
        "dur": 345.29,
        "conv": 0.0403,
        "trans": 595,
        "revenue": 355435.04
      },
      {
        "id": "lp-1",
        "name": "/login.php",
        "sessions": 4323,
        "pctNew": 0.3701,
        "newUsers": 1600,
        "bounce": 0.3273,
        "pages": 3.96,
        "dur": 158.46,
        "conv": 0.0109,
        "trans": 47,
        "revenue": 53961.34
      },
      {
        "id": "lp-2",
        "name": "/ue48h6400akxxu-samsung-ue48h6400--3d-led-tv--1080p-fullhd.p1039405.html?ref=PLA",
        "sessions": 2502,
        "pctNew": 0.6575,
        "newUsers": 1645,
        "bounce": 0.7142,
        "pages": 2.27,
        "dur": 95.7,
        "conv": 0.0088,
        "trans": 22,
        "revenue": 10091.26
      },
      {
        "id": "lp-3",
        "name": "/ue48h6400akxxu-samsung-ue48h6400--3d-led-tv--1080p-fullhd.p1039405.html",
        "sessions": 2073,
        "pctNew": 0.7106,
        "newUsers": 1473,
        "bounce": 0.7617,
        "pages": 1.95,
        "dur": 92.77,
        "conv": 0.0024,
        "trans": 5,
        "revenue": 2209.05
      },
      {
        "id": "lp-4",
        "name": "/shopping_cart.php",
        "sessions": 2024,
        "pctNew": 0.083,
        "newUsers": 168,
        "bounce": 0.3528,
        "pages": 5.29,
        "dur": 272.73,
        "conv": 0.1858,
        "trans": 376,
        "revenue": 165321.17
      },
      {
        "id": "lp-5",
        "name": "/ue55ju6400kxxu-samsung-ue55ju6400k--55-led-tv.p1137074.html?ref=PLA",
        "sessions": 1035,
        "pctNew": 0.6377,
        "newUsers": 660,
        "bounce": 0.7053,
        "pages": 2.29,
        "dur": 94,
        "conv": 0.0145,
        "trans": 15,
        "revenue": 11477.94
      },
      {
        "id": "lp-6",
        "name": "/ue48j6300akxxu-samsung-ue48j6300ak--48-led-tv.p1130877.html?ref=PLA",
        "sessions": 981,
        "pctNew": 0.7829,
        "newUsers": 768,
        "bounce": 0.7829,
        "pages": 1.93,
        "dur": 69.47,
        "conv": 0.0082,
        "trans": 8,
        "revenue": 4080.85
      },
      {
        "id": "lp-7",
        "name": "/ue48h6400akxxu-samsung-ue48h6400--3d-led-tv--1080p-fullhd.p1039405.html?ref=ID",
        "sessions": 971,
        "pctNew": 0.6818,
        "newUsers": 662,
        "bounce": 0.7662,
        "pages": 1.74,
        "dur": 86.29,
        "conv": 0.001,
        "trans": 1,
        "revenue": 500.86
      },
      {
        "id": "lp-8",
        "name": "/ue40ju6400kxxu-samsung-ue40ju6400k--40-led-tv.p1130875.html?ref=PLA",
        "sessions": 877,
        "pctNew": 0.7446,
        "newUsers": 653,
        "bounce": 0.7149,
        "pages": 2.2,
        "dur": 96.4,
        "conv": 0.0103,
        "trans": 9,
        "revenue": 4346.05
      },
      {
        "id": "lp-9",
        "name": "/ue40ju6400kxxu-samsung-40-uhd-led-tv-900-pqi-smart-quad-core-games-wifi-mirror-app-casting-ble-multiroom-link.p1130875.html?ref=PLA",
        "sessions": 866,
        "pctNew": 0.7506,
        "newUsers": 650,
        "bounce": 0.7079,
        "pages": 2.29,
        "dur": 88.71,
        "conv": 0.015,
        "trans": 13,
        "revenue": 6289.82
      },
      {
        "id": "lp-10",
        "name": "/1rr000109-tomtom-runner.p1166967.html?ref=PLA",
        "sessions": 819,
        "pctNew": 0.7546,
        "newUsers": 618,
        "bounce": 0.746,
        "pages": 2.13,
        "dur": 75.04,
        "conv": 0.0037,
        "trans": 3,
        "revenue": 197.64
      },
      {
        "id": "lp-11",
        "name": "/ue32j5500akxxu-samsung-32-full-hd-led-tv-300-pqi-smart-quad-core-wifi-mirror-app-casting.p1130897.html?ref=PLA",
        "sessions": 818,
        "pctNew": 0.7029,
        "newUsers": 575,
        "bounce": 0.7225,
        "pages": 2.19,
        "dur": 84.97,
        "conv": 0.0208,
        "trans": 17,
        "revenue": 4527.74
      },
      {
        "id": "lp-12",
        "name": "/boxnuc5i7ryh-intel-next-unit-of-computing-kit-nuc5i7ryh--core-i7-5557u-31-ghz--0-mb--0-gb.p1133988.html?ref=PLA",
        "sessions": 780,
        "pctNew": 0.5538,
        "newUsers": 432,
        "bounce": 0.7692,
        "pages": 2.07,
        "dur": 86.12,
        "conv": 0.009,
        "trans": 7,
        "revenue": 3315.92
      },
      {
        "id": "lp-13",
        "name": "/ue55ju6400kxxu-samsung-55-inch-uhd-led-tv--900-pqi--smart-quad-core--games--wifi--mirror-app-casting--ble--multiroom-link.p1137074.html?ref=PLA",
        "sessions": 676,
        "pctNew": 0.645,
        "newUsers": 436,
        "bounce": 0.6953,
        "pages": 2.18,
        "dur": 101.54,
        "conv": 0.0163,
        "trans": 11,
        "revenue": 8980.98
      },
      {
        "id": "lp-14",
        "name": "/contact",
        "sessions": 638,
        "pctNew": 0.3809,
        "newUsers": 243,
        "bounce": 0.4279,
        "pages": 4.08,
        "dur": 214.36,
        "conv": 0.011,
        "trans": 7,
        "revenue": 1227.31
      },
      {
        "id": "lp-15",
        "name": "/ue55ju6500kxxu-samsung-ue55ju6500k--55-led-tv.p1130868.html?ref=PLA",
        "sessions": 628,
        "pctNew": 0.7118,
        "newUsers": 447,
        "bounce": 0.7468,
        "pages": 2.03,
        "dur": 74.1,
        "conv": 0.0032,
        "trans": 2,
        "revenue": 1825.58
      },
      {
        "id": "lp-16",
        "name": "/ue48j5500akxxu-samsung-ue48j5500ak--48-led-tv.p1130878.html?ref=PLA",
        "sessions": 620,
        "pctNew": 0.6613,
        "newUsers": 410,
        "bounce": 0.6919,
        "pages": 2.42,
        "dur": 105.13,
        "conv": 0.0145,
        "trans": 9,
        "revenue": 3850.46
      },
      {
        "id": "lp-17",
        "name": "/ue32h6400akxxu-samsung-ue32h6400--32-3d-led-tv--smart-tv--1080p-fullhd.p1039396.html?ref=PLA",
        "sessions": 615,
        "pctNew": 0.6992,
        "newUsers": 430,
        "bounce": 0.6553,
        "pages": 2.59,
        "dur": 100.6,
        "conv": 0.0228,
        "trans": 14,
        "revenue": 4522.27
      },
      {
        "id": "lp-18",
        "name": "/kdl75w855cbu-kdl75w855cbu.p1153758.html?ref=PLA",
        "sessions": 605,
        "pctNew": 0.724,
        "newUsers": 438,
        "bounce": 0.8033,
        "pages": 1.81,
        "dur": 67.26,
        "conv": 0.0066,
        "trans": 4,
        "revenue": 7697.91
      },
      {
        "id": "lp-19",
        "name": "/ue32j6300akxxu-samsung-ue32j6300ak--32-led-tv.p1130898.html?ref=PLA",
        "sessions": 572,
        "pctNew": 0.7238,
        "newUsers": 414,
        "bounce": 0.7203,
        "pages": 2.33,
        "dur": 95.16,
        "conv": 0.0157,
        "trans": 9,
        "revenue": 2830.25
      },
      {
        "id": "lp-20",
        "name": "/ue55ju6800kxxu-samsung-ue55ju6800k--55-led-tv.p1166504.html?ref=PLA",
        "sessions": 532,
        "pctNew": 0.718,
        "newUsers": 382,
        "bounce": 0.6955,
        "pages": 2.3,
        "dur": 81.43,
        "conv": 0.0094,
        "trans": 5,
        "revenue": 4359.91
      },
      {
        "id": "lp-21",
        "name": "/502660-archos-smart-home-starter-pack--home-automation-kit--wireless--bluetooth-40-le.p1121802.html?ref=PLA",
        "sessions": 509,
        "pctNew": 0.9214,
        "newUsers": 469,
        "bounce": 0.9116,
        "pages": 1.24,
        "dur": 11.1,
        "conv": 0,
        "trans": 0,
        "revenue": 0
      },
      {
        "id": "lp-other",
        "name": "(all other landing pages)",
        "sessions": 191906,
        "pctNew": 0.687,
        "newUsers": 131842,
        "bounce": 0.8055,
        "pages": 1.85,
        "dur": 67.97,
        "conv": 0.021,
        "trans": 4024,
        "revenue": 2629947.32
      }
    ]
  },
  "products": {
    "rows": [
      {
        "id": "pr-0",
        "name": "Kingston SSDNow V300 - solid state drive - 120 GB - SATA 6Gb/s",
        "qty": 343,
        "purchases": 4,
        "revenue": 9812.47,
        "avgPrice": 28.61,
        "avgQty": 85.75
      },
      {
        "id": "pr-1",
        "name": "Microsoft Wired Desktop 600 - keyboard and mouse set - English -",
        "qty": 282,
        "purchases": 4,
        "revenue": 3936.29,
        "avgPrice": 13.96,
        "avgQty": 70.5
      },
      {
        "id": "pr-2",
        "name": "Belkin patch cable - 1 m - black",
        "qty": 200,
        "purchases": 1,
        "revenue": 158,
        "avgPrice": 0.79,
        "avgQty": 200
      },
      {
        "id": "pr-3",
        "name": "Kingston ValueRAM - DDR3L - 4 GB - SO DIMM 204-pin",
        "qty": 200,
        "purchases": 2,
        "revenue": 2800,
        "avgPrice": 14,
        "avgQty": 100
      },
      {
        "id": "pr-4",
        "name": "Asus Un42 Vivomini Pc Barebone Pc Celeron (2957u) 1.4ghz No Odd",
        "qty": 190,
        "purchases": 2,
        "revenue": 18335,
        "avgPrice": 96.5,
        "avgQty": 95
      },
      {
        "id": "pr-5",
        "name": "Dell Active Stylus - stylus",
        "qty": 153,
        "purchases": 11,
        "revenue": 2605.59,
        "avgPrice": 17.03,
        "avgQty": 13.91
      },
      {
        "id": "pr-6",
        "name": "TESLA 500W (500 Watt PSU, Retail, Quiet + Thermal Control, 12cm",
        "qty": 116,
        "purchases": 4,
        "revenue": 1282,
        "avgPrice": 11.05,
        "avgQty": 29
      },
      {
        "id": "pr-7",
        "name": "Custom Shipping Charge",
        "qty": 104,
        "purchases": 104,
        "revenue": 2243.34,
        "avgPrice": 21.57,
        "avgQty": 1
      },
      {
        "id": "pr-8",
        "name": "Corsair Neutron Series GTX - solid state drive - 120 GB - SATA 6",
        "qty": 102,
        "purchases": 2,
        "revenue": 6936,
        "avgPrice": 68,
        "avgQty": 51
      },
      {
        "id": "pr-9",
        "name": "GZ-M5 2-Bay Micro-ATX Case SECC 8CM Fan 2 x USB2.0",
        "qty": 102,
        "purchases": 3,
        "revenue": 1532,
        "avgPrice": 15.02,
        "avgQty": 34
      },
      {
        "id": "pr-10",
        "name": "AOC M2870VQ - LED monitor - 28\"",
        "qty": 101,
        "purchases": 2,
        "revenue": 12337.7,
        "avgPrice": 122.16,
        "avgQty": 50.5
      },
      {
        "id": "pr-11",
        "name": "HGST Ultrastar 7K4000 HUS724030ALE640 - hard drive - 3 TB - SATA",
        "qty": 101,
        "purchases": 3,
        "revenue": 13008.2,
        "avgPrice": 128.79,
        "avgQty": 33.67
      },
      {
        "id": "pr-12",
        "name": "Kingston SSDNow mS200 - solid state drive - 60 GB - SATA 6Gb/s",
        "qty": 100,
        "purchases": 1,
        "revenue": 2640,
        "avgPrice": 26.4,
        "avgQty": 100
      },
      {
        "id": "pr-13",
        "name": "Kingston SSDNow mS200 - solid state drive - 60 GB - SATA-600",
        "qty": 100,
        "purchases": 1,
        "revenue": 2640,
        "avgPrice": 26.4,
        "avgQty": 100
      },
      {
        "id": "pr-14",
        "name": "Samsung UE48H6400 - 3D LED TV - 1080p (FullHD)",
        "qty": 98,
        "purchases": 96,
        "revenue": 36854.58,
        "avgPrice": 376.07,
        "avgQty": 1.02
      },
      {
        "id": "pr-15",
        "name": "Cisco Aironet 2702i Controller-based - radio access point",
        "qty": 77,
        "purchases": 1,
        "revenue": 22946,
        "avgPrice": 298,
        "avgQty": 77
      },
      {
        "id": "pr-16",
        "name": "Samsung UE40JU6400K - 40\" LED TV",
        "qty": 63,
        "purchases": 62,
        "revenue": 25118.89,
        "avgPrice": 398.71,
        "avgQty": 1.02
      },
      {
        "id": "pr-b10",
        "name": "Apple iPad Air Wi-Fi - tablet - 16 GB - 9.7\"",
        "qty": 60,
        "purchases": 1,
        "revenue": 14880,
        "avgPrice": 248,
        "avgQty": 60
      },
      {
        "id": "pr-17",
        "name": "Samsung UE55JU6400K - 55\" LED TV",
        "qty": 53,
        "purchases": 52,
        "revenue": 34382.14,
        "avgPrice": 648.72,
        "avgQty": 1.02
      },
      {
        "id": "pr-b0",
        "name": "Samsung UE32J5500AK - 32\" LED TV",
        "qty": 46,
        "purchases": 39,
        "revenue": 9059.42,
        "avgPrice": 196.94,
        "avgQty": 1.18
      },
      {
        "id": "pr-b3",
        "name": "APC Smart-UPS 1500 LCD - UPS - 1 kW - 1500 VA",
        "qty": 30,
        "purchases": 23,
        "revenue": 9256.07,
        "avgPrice": 308.54,
        "avgQty": 1.3
      },
      {
        "id": "pr-b1",
        "name": "Samsung UE32H6400 - 32\" 3D LED TV - Smart TV - 1080p (FullHD)",
        "qty": 28,
        "purchases": 28,
        "revenue": 7240.62,
        "avgPrice": 258.59,
        "avgQty": 1
      },
      {
        "id": "pr-b2",
        "name": "TomTom Runner - GPS/GLONASS navigator",
        "qty": 28,
        "purchases": 27,
        "revenue": 1536.24,
        "avgPrice": 54.87,
        "avgQty": 1.04
      },
      {
        "id": "pr-b7",
        "name": "Owc 2.5 Drive Sled/ 09 10 Macpro Model",
        "qty": 26,
        "purchases": 17,
        "revenue": 253.1,
        "avgPrice": 9.73,
        "avgQty": 1.53
      },
      {
        "id": "pr-b6",
        "name": "DrayTek Vigor 2860n Triple WAN ADSL2+/VDSL2 Wireless N Router w/",
        "qty": 23,
        "purchases": 19,
        "revenue": 3908.85,
        "avgPrice": 169.95,
        "avgQty": 1.21
      },
      {
        "id": "pr-b4",
        "name": "Samsung UE48J6300AK - 48\" LED TV",
        "qty": 22,
        "purchases": 22,
        "revenue": 9164.21,
        "avgPrice": 416.56,
        "avgQty": 1
      },
      {
        "id": "pr-b5",
        "name": "Samsung UE48J5500AK - 48\" LED TV",
        "qty": 22,
        "purchases": 21,
        "revenue": 7748.88,
        "avgPrice": 352.22,
        "avgQty": 1.05
      },
      {
        "id": "pr-b11",
        "name": "Apple iPad mini 2 Wi-Fi - tablet - 16 GB - 7.9\"",
        "qty": 20,
        "purchases": 1,
        "revenue": 3840,
        "avgPrice": 192,
        "avgQty": 20
      },
      {
        "id": "pr-b8",
        "name": "Intel Next Unit of Computing Kit NUC5I7RYH - Core i7 5557U 3.1 G",
        "qty": 18,
        "purchases": 17,
        "revenue": 5557.29,
        "avgPrice": 308.74,
        "avgQty": 1.06
      },
      {
        "id": "pr-b9",
        "name": "Samsung UE32J6300AK - 32\" LED TV",
        "qty": 17,
        "purchases": 17,
        "revenue": 4467.83,
        "avgPrice": 262.81,
        "avgQty": 1
      },
      {
        "id": "pr-18",
        "name": "Sony KDL-75W855C - 75\" 3D LED TV",
        "qty": 15,
        "purchases": 15,
        "revenue": 23981.25,
        "avgPrice": 1598.75,
        "avgQty": 1
      },
      {
        "id": "pr-19",
        "name": "Electronic HP Care Pack 6-Hour Call-To-Repair Proactive Care Ser",
        "qty": 11,
        "purchases": 11,
        "revenue": 36028.32,
        "avgPrice": 3275.3,
        "avgQty": 1
      },
      {
        "id": "pr-20",
        "name": "HP Foundation Care Call-To-Repair Service with Comprehensive Def",
        "qty": 5,
        "purchases": 5,
        "revenue": 62401.03,
        "avgPrice": 12480.21,
        "avgQty": 1
      },
      {
        "id": "pr-21",
        "name": "Electronic HP Care Pack 4-hour 24x7 Proactive Care Service - ext",
        "qty": 4,
        "purchases": 4,
        "revenue": 229450.83,
        "avgPrice": 57362.71,
        "avgQty": 1
      },
      {
        "id": "pr-22",
        "name": "HP Foundation Care 24x7 Service with Comprehensive Defective Mat",
        "qty": 3,
        "purchases": 3,
        "revenue": 147195.35,
        "avgPrice": 49065.12,
        "avgQty": 1
      },
      {
        "id": "pr-23",
        "name": "HP Foundation Care Next Business Day Service with Comprehensive",
        "qty": 3,
        "purchases": 3,
        "revenue": 28532.75,
        "avgPrice": 9510.92,
        "avgQty": 1
      },
      {
        "id": "pr-other",
        "name": "(all other products)",
        "qty": 12435,
        "purchases": 5819,
        "revenue": 1809628.9,
        "avgPrice": 145.53,
        "avgQty": 2.14
      }
    ]
  },
  "plaSummary": {
    "basis": "Named ?ref=PLA rows in the 1,000-row Landing Pages export only; GA truncated the long tail (pages under 29 sessions), so these aggregates are a lower bound on all Shopping-ad traffic.",
    "exportedRows": 1000,
    "exportedSessions": 102363,
    "reportSessions": 230128,
    "pages": 888,
    "products": 874,
    "sessions": 70591,
    "bounce": 0.8237,
    "dur": 53.96,
    "trans": 602,
    "revenue": 247891.04,
    "conv": 0.0085,
    "zeroSaleOver200": 14,
    "zeroSaleOver200Products": 14,
    "zeroSaleOver200Pages": [
      {
        "name": "/502660-archos-smart-home-starter-pack--home-automation-kit--wireless--bluetooth-40-le.p1121802.html?ref=PLA",
        "sessions": 509,
        "bounce": 0.9116,
        "dur": 11.1
      },
      {
        "name": "/1004615-binatone-eclipse-plus--white-single-phone.p908498.html?ref=PLA",
        "sessions": 411,
        "bounce": 0.9294,
        "dur": 10.71
      },
      {
        "name": "/580adbq-venue-keyboard.p1128068.html?ref=PLA",
        "sessions": 310,
        "bounce": 0.8839,
        "dur": 15.56
      },
      {
        "name": "/g803000lscgb2-cherry-classic-line-g803000--keyboard--ps2-usb--uk--black.p575022.html?ref=PLA",
        "sessions": 302,
        "bounce": 0.8576,
        "dur": 28.75
      },
      {
        "name": "/90msvdy0g0eay20t-z9ped8-ws-2xs2011-atx.p1081074.html?ref=PLA",
        "sessions": 299,
        "bounce": 0.9231,
        "dur": 23.31
      },
      {
        "name": "/s3520bu33er-startechcom-usb-3-esata-dual-35-sata-iii-hdd-raid-enclosure-uasp--hard-drive-array--2-bays--sata600---superspeed-usb-30-serial-ata600-external.p1009327.html?ref=PLA",
        "sessions": 278,
        "bounce": 0.9065,
        "dur": 11.51
      },
      {
        "name": "/ls34e790cnsen-ls34e790cnsen-34-curved-monitor-3440x1440-uwqhd-30001-4ms-300cdm2-219-60hz.p1111477.html?ref=PLA",
        "sessions": 274,
        "bounce": 0.9307,
        "dur": 13.63
      },
      {
        "name": "/90ms0071m00150-asus-bbone-gaming-core-i7--4510-processor.p1088650.html?ref=PLA",
        "sessions": 260,
        "bounce": 0.9115,
        "dur": 10.75
      },
      {
        "name": "/780003b21-hp-dl360-gen9-e52699v3-kit.p1094378.html?ref=PLA",
        "sessions": 259,
        "bounce": 0.9459,
        "dur": 12.28
      },
      {
        "name": "/smg925fzgabtu-samsung-galaxy-s6-edge--smg925f--4g--32-gb--51--2560-x-1440-pixels--577-ppi---super-amoled--16-mpix--5mpix-front-camera---android--emerald-green.p1161407.html?ref=PLA",
        "sessions": 257,
        "bounce": 0.8249,
        "dur": 44.53
      },
      {
        "name": "/f8w305vfc00-belkin-vans-waffle-sole-case--protective-case-for-digital-player--silicone--for-apple-ipod-touch-5g.p945881.html?ref=PLA",
        "sessions": 235,
        "bounce": 0.9787,
        "dur": 1.46
      },
      {
        "name": "/g20ajuk007s-g20i74790-16gb-128gb-ssd-2tb-w81.p1146217.html?ref=PLA",
        "sessions": 221,
        "bounce": 0.8914,
        "dur": 20.05
      },
      {
        "name": "/si10x-wharsi10x.p1060567.html?ref=PLA",
        "sessions": 218,
        "bounce": 0.9633,
        "dur": 30.8
      },
      {
        "name": "/smn915fzkybtu-samsung-note-edge-32gb-56-display-quad-core--super-amoled-android-battery--3000-mah-removable-3gb-ram-micro-sd-up-to-128gb-resolution-560-x-1440160-quad-hd-camera-cmo.p1153586.html?ref=PLA",
        "sessions": 212,
        "bounce": 0.9057,
        "dur": 21.21
      }
    ],
    "worst": {
      "name": "/502660-archos-smart-home-starter-pack--home-automation-kit--wireless--bluetooth-40-le.p1121802.html?ref=PLA",
      "sessions": 509,
      "bounce": 0.9116,
      "dur": 11.1
    }
  }
};
